name: Build CTE

on:
  push:
    branches:
      - main
      - gh_workflow
    #tags:
    #  # push a tagged commit to trigger a release...
    #  # e.g. git tag -am v0.0.1 "v0.0.1"; git push --follow-tags
    #  - "v*"

# cancel in-progress runs that use the same workflow and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build
    #if: success() && startsWith(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    runs-on: ubuntu-latest

    permissions:
      # This permission allows writing releases
      contents: write

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #- name: Release the source on GitHub
      #  uses: softprops/action-gh-release@v2
      #  with:
      #    files: './*'

      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          mamba-version: "*"
          channels: conda-forge, nodefaults
          activate-environment: package-build

      - name: Build conda package
        shell: bash -el {0}
        run: |
          conda activate package-build
          conda install conda-build anaconda-client
          ls -lrth
          conda build conda-recipe -c nvidia/label/cuda-11.7.0 -c pytorch -c conda-forge

